### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by BrunoHldr** [BrunoHldr/GCMS-Bruno-Holder#2]
- [ ] #3

- [ ] Criar projeto local

- [ ] Criar repositório local e realizar commits

- [ ] Subir alterações para o repositório remoto

- [ ] Fazer alterações no repositório da turma

@ramidedantas

**Comment by ramidedantas** [comment]
Ok, deixar aberto.
